name: Build and Release

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.11"
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]

      - name: Build with Nuitka
        uses: Nuitka/Nuitka-Action@v1.4
        with:
          script-name: main.py
          mode: standalone
          output-dir: build
          include-package: paypay2mf
          include-package-data: paypay2mf

      - name: Zip artifact
        run: |
          $TAG = "${{ github.event.release.tag_name }}"
          $ZIP_NAME = "paypay2mf-$TAG.zip"
          $ARTIFACTS = @(
            "build/main.dist/*"
            "README.md"
            "LICENSE"
            "config_sample.yml"
            "mf_categories_sample.yml"
          )
          Compress-Archive -Path $ARTIFACTS -DestinationPath $ZIP_NAME

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: paypay2mf-${{ github.event.release.tag_name }}.zip
